rootProject.name = "dynameta"
include("server")
include("datastore")
include("postgres-connect")
include("resource-api")
include("controller-api")
include("repository")
include("utils")
include("core")
include("controller-api-v2")
include("core-v2")
include("base-plugin")
