rootProject.name = "dynameta"
include("server")
include("datastore")
include("postgres-connect")
include("resource-api")
include("controller-api")
include("repository")
include("utils")
include("core-deprecated")
include("plugin-api")
include("core")
include("base-plugin")
include("dummy-test-plugin")
